#!/usr/bin/env bash
set -euo pipefail

# vai agent loop — OpenAI Codex, bare-shell mode
# Generated by `vai agent loop init`
#
# Repository : {{REPO_NAME}}
# Server     : {{SERVER_URL}}

# Change to the repository root (three levels up from .vai/agents/codex/).
cd "$(dirname "$0")/../../.."

# Load .env from the repository root.
if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  source .env
  set +a
fi

: "${VAI_API_KEY:?VAI_API_KEY not set — add it to .env or export it}"
: "${OPENAI_API_KEY:?OPENAI_API_KEY not set — add your OpenAI API key to .env}"

MAX_ITERATIONS="${MAX_ITERATIONS:-100}"
echo "Starting Codex agent loop for {{REPO_NAME}} (max ${MAX_ITERATIONS} iterations)"

for ((i = 1; i <= MAX_ITERATIONS; i++)); do
  echo ""
  echo "=== Iteration ${i}/${MAX_ITERATIONS} ==="

  if ! vai agent claim; then
    echo "No more issues to work on — loop complete."
    exit 0
  fi

  if ! vai agent download ./work; then
    echo "download failed, resetting workspace and continuing loop" >&2
    vai agent reset
    rm -rf ./work
    continue
  fi

  # Run Codex; pipe in the vai prompt.
  vai agent prompt | codex \
    || true

  if vai agent verify ./work; then
    submit_exit=0
    vai agent submit ./work || submit_exit=$?
    case $submit_exit in
      0) ;;  # submitted successfully
      3)
        echo "Workspace empty — closing issue as already resolved."
        ISSUE_ID=$(vai --json agent status | jq -r .issue_id)
        if [ -n "$ISSUE_ID" ] && [ "$ISSUE_ID" != "null" ]; then
          vai issue close "$ISSUE_ID" --resolution resolved || true
        fi
        ;;
      *)
        echo "Submit failed (exit ${submit_exit}) — resetting workspace." >&2
        vai agent reset
        ;;
    esac
  else
    echo "Verification failed — resetting workspace."
    vai agent reset
  fi

  rm -rf ./work
done

echo "Reached max iterations (${MAX_ITERATIONS}). Exiting."
