#!/usr/bin/env bash
set -euo pipefail

# vai agent loop — custom agent
# Generated by `vai agent loop init`
#
# Repository : {{REPO_NAME}}
# Server     : {{SERVER_URL}}
#
# TODO: Fill in your agent invocation below.

# Change to the repository root (three levels up from .vai/agents/custom/).
cd "$(dirname "$0")/../../.."

# Load .env from the repository root.
if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  source .env
  set +a
fi

: "${VAI_API_KEY:?VAI_API_KEY not set — add it to .env or export it}"
# TODO: Add provider-token checks for your agent, e.g.:
# : "${MY_AGENT_TOKEN:?MY_AGENT_TOKEN not set}"

MAX_ITERATIONS="${MAX_ITERATIONS:-100}"
echo "Starting custom agent loop for {{REPO_NAME}} (max ${MAX_ITERATIONS} iterations)"

for ((i = 1; i <= MAX_ITERATIONS; i++)); do
  echo ""
  echo "=== Iteration ${i}/${MAX_ITERATIONS} ==="

  if ! vai agent claim; then
    echo "No more issues to work on — loop complete."
    exit 0
  fi

  if ! vai agent download ./work; then
    echo "download failed, resetting workspace and continuing loop" >&2
    vai agent reset
    rm -rf ./work
    continue
  fi

  # TODO: Invoke your agent here. The vai prompt is piped to stdin.
  # Example:
  #   vai agent prompt | my-agent --workdir ./work || true
  echo "ERROR: no agent invocation configured. Edit $(dirname "$0")/loop.sh." >&2
  exit 1

  if vai agent verify ./work; then
    vai agent submit ./work
  else
    echo "Verification failed — resetting workspace."
    vai agent reset
  fi

  rm -rf ./work
done

echo "Reached max iterations (${MAX_ITERATIONS}). Exiting."
