#!/usr/bin/env bash
set -euo pipefail

# vai agent loop — OpenAI Codex, Docker mode
# Generated by `vai agent loop init`
#
# Repository : {{REPO_NAME}}
# Server     : {{SERVER_URL}}

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
AGENT_DIR="$(cd "$(dirname "$0")" && pwd)"
IMAGE_TAG="vai-agent-{{AGENT_NAME}}:latest"

# Load .env from the repository root.
if [ -f "${REPO_ROOT}/.env" ]; then
  set -a
  # shellcheck source=/dev/null
  source "${REPO_ROOT}/.env"
  set +a
fi

: "${VAI_API_KEY:?VAI_API_KEY not set — add it to .env or export it}"
: "${OPENAI_API_KEY:?OPENAI_API_KEY not set — add your OpenAI API key to .env}"

# Build (or rebuild) the agent Docker image.
echo "Building agent image ${IMAGE_TAG} ..."
docker build -t "${IMAGE_TAG}" "${AGENT_DIR}"

echo "Starting Codex agent loop for {{REPO_NAME}} inside Docker"

docker run --rm \
  --name "vai-agent-{{AGENT_NAME}}-$$" \
  -v "${REPO_ROOT}:/home/agent/repo" \
  -e VAI_API_KEY="${VAI_API_KEY}" \
  -e OPENAI_API_KEY="${OPENAI_API_KEY}" \
  -e MAX_ITERATIONS="${MAX_ITERATIONS:-100}" \
  -e VAI_SERVER_URL="{{SERVER_URL}}" \
  "${IMAGE_TAG}"
